---
- hosts: wp_nodes
  become: yes
  vars_files:
    - vars/main.yaml
  tasks:
    - include_tasks: tasks/db_related.yaml
    - include_tasks: tasks/os_packages.yaml
    - include_tasks: tasks/wp_related.yaml

- hosts: load_balancer
  become: yes
  vars:
    app_ips:
      - 172.31.37.40:80
      - 172.31.12.126:80
  tasks:
    - name: install epel
      yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: install nginx
      yum:
        name: nginx
        state: present
    - name: put nginx conf
      template:
        src: files/lb.conf
        dest: /etc/nginx/conf.d/blog.conf
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded
    
    





