---
- name: "install http server"
  yum:
    name: httpd
    state: present

- name: "install EPEL"
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
- name: "install php repo"
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present
- name: "install php packages"
  yum:
    name: php80-php, php80, php80-php-mysqlnd, php80-php-pecl-mysql
    state: present